---
language: python

python:
  - "2.7"

install:
  - pip install ansible

script:
  - printf '[defaults]\nroles_path=../' >ansible.cfg
  - ansible --version
  - ansible-playbook tests/test.yml -i tests/inventory --syntax-check

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
